title: Mio's pages
author: Mio Galang
email: mio@galang.co
description: > # this means to ignore newlines until "baseurl:"
  This is the best site ever, in the history of the world

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
